spring:
  datasource:
    url: jdbc:mysql://security-db-test.c7j4gjsdenq5.ap-southeast-1.rds.amazonaws.com/dcrop_hightech
    username: admin
    password: Egan130599
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true