spring:
  application:
    name: ACCOUNT-WS
  datasource:
    url: jdbc:mysql://localhost:3306/e-commercy
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka